# Generated by Django 4.0.5 on 2022-06-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usertype_alter_user_email_alter_user_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hobby',
        ),
    ]
